language: ruby
env:
  - DB=sqlite
before_script:
  - cp config/database.travis.yml config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec -f p
  - bundle exec rubocop
  - bundle exec brakeman
